# Generated by Django 4.2.3 on 2023-08-11 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', message='Enter a Valid Indian password Number')])),
                ('phone', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
